// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.model;

import au.gov.nsw.records.digitalarchive.model.Pathway;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Pathway_Roo_Configurable {
    
    declare @type: Pathway: @Configurable;
    
}
