// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.model;

import au.gov.nsw.records.digitalarchive.model.Purpose;

privileged aspect Purpose_Roo_JavaBean {
    
    public String Purpose.getName() {
        return this.name;
    }
    
    public void Purpose.setName(String name) {
        this.name = name;
    }
    
}
